#!/bin/bash

# 根据扩展名选择对应的 WPS 程序
file=$1
case $file in
*.doc | *.docx) exe=/usr/bin/wps ;;
*.xls | *.xlsx) exe=/usr/bin/et ;;
*.ppt | *.pptx) exe=/usr/bin/wpp ;;
*.pdf) exe=/usr/bin/wpspdf ;;
*) exe=/usr/bin/wps ;;
esac

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

binds=()
for dir in kingsoft Kingsoft; do
  if [ ! -d "${XDG_CONFIG_HOME}/$dir" ]; then mkdir "${XDG_CONFIG_HOME}/$dir"; fi
  binds+=(--bind "${XDG_CONFIG_HOME}/$dir" "${XDG_CONFIG_HOME}/$dir")
done
binds+=(--bind "${XDG_CONFIG_HOME}/mimeapps.list" "${XDG_CONFIG_HOME}/mimeapps.list")
binds+=(--bind "${XDG_DATA_HOME}/Kingsoft" "${XDG_DATA_HOME}/Kingsoft")
DOC_DIR=$(xdg-user-dir DOCUMENTS)
binds+=(--bind $DOC_DIR $DOC_DIR)
binds+=(--bind /home/texsd/.local/share/Kingsoft/ /home/texsd/.local/share/Kingsoft/)

# bind mount 需要操作的文件
if [[ -f "$file" ]]; then
  file_path="$(realpath "$(dirname "$file")")"
  binds+=(--bind "$file_path" "$file_path")
fi

# 1. 创建一个宿主机上的共享目录，专门用来放 WPS 的通信套接字 (Socket)
# 这样不同的沙箱实例就能在这个特定目录下“碰头”了
WPS_TMP_DIR="/tmp/wps-sandbox-${UID}"
mkdir -p "$WPS_TMP_DIR"

exec bwrap --new-session --unshare-user-try --unshare-pid --unshare-cgroup-try --die-with-parent \
  --ro-bind / / \
  --tmpfs /home --proc /proc --dev /dev \
  --dev-bind /dev/dri /dev/dri \
  --ro-bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
  --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
  --ro-bind "${XDG_DATA_HOME}/fonts" "${XDG_DATA_HOME}/fonts" \
  --tmpfs /tmp \
  --bind "$WPS_TMP_DIR" /tmp \
  "${binds[@]}" \
  "$exe" "$@"
